U<?php
	require_once("_header.php");
?>

			
				<br>
				<h3>Here are some stats about the Monroe 911 feed scraper system:</h3>
			
				<?
			
					include_once("./tools/StatusManager.class.php");
					
					// create a database tool to use to pull information from the database
					//$db = new Database();
					
					$statusManager = new StatusManager();
					
					//
					// System Stats
					//
					
					// get the total number of times the scraper has run
					$runCount = $statusManager->GetNumberOfRuns();
					// get the total number of unique entrees in the database
					$uniqueIncidents = $statusManager->GetTotalUniqueIncidents();
					// get the total number of event types logged into the system
					$totalEventTypes = $statusManager->GetTotalEventTypes();
					// get the total number of status types logged into the system
					$totalStatusTypes = $statusManager->GetTotalStatusTypes();
					
					
					// get the total number of API calls that have been made
					//$apicalls = $db->GetNumberOfAPICalls();
					// get the number of unique api users today
					//$totalUniqueApiUsers = $db->GetTotalUniqueAPIUsers();
					// get the number of unique api users today
					//$uniqueApiUsersToday = $db->GetUniqueAPIUsersToday();
					// get the average querytime today
					//$averageQueryToday = $db->GetAverageQueryToday();
					
					// display the results from the database
					//echo '<p class="tab">';
					//echo "<b><br>System Stats: </b><br>";
					//echo '</p>';
					//echo '<p class="tab2">';
					
					//echo "Total number of API calls: " . $apicalls . "<br>";
					//echo "Total Unique API users: " . $totalUniqueApiUsers . "<br>";
					//echo "Unique API Users Today: " . $uniqueApiUsersToday . "<br>";
					//echo "Average Query Time Today: " . number_format($averageQueryToday,4) . " Seconds<br>";
					//echo '</p>';
					
					
					//
					// Data Stats
					//
					
					
					
					//echo '<p class="tab">';
					//echo "<b>System Stats: </b><br>";
					//echo '</p>';
					echo '<br>';
					echo '<p class="tab">';
					echo "Total scraper runs: <b>" . $runCount . "</b><br>";
					echo "Total Unique Incidents: <b>" . $uniqueIncidents . "</b><br>";
					echo "Total Incident Types: <b>" . $totalEventTypes . "</b><br>";
					echo "Total Status Types: <b>" . $totalStatusTypes . "</b><br>";
					echo '</p>';
					
				?>
			
				<br>
				<h3>So what does all that mean?</h3>
				<br>
				
				<p class="tab">
				The above data represents the current status of this site and its associated web scrapers.  What is a web scraper?  In this case, there are pieces of code that go
				out on the internet and collect information from the Monroe County, NY dispatch center and collate it.  If you would like more information about the Monroe County dispatch
				center, check out the <a href="about.php">About</a> page.  If you would like to know more about the data that is being collected, and how you can use it, check out
				the <a href="developers.php">Developers</a> page.
				</p>
				<br>
				<br>
				
				<h3>System Stats</h3>
				<br>
				
				<p class="tab">
				<b>Total Scraper Runs</b>
				</p>
				<p class="tab2">
				this represents the total number of times the web scrapers have run.  The scrapers run every 60 seconds to ensure all of the information that the
				dispatch center is providing is captured, and nothing is missed.
				</p>
				<br>
				
				<p class="tab">
				<b>Total Unique Incidents</b>
				</p>
				<p class="tab2">
				An incident is defined as a unique incident ID being generated by the 911 dispatch center.  If a call comes in for a Motor Vehicle Accident, it is possible that Monroe County 
				Police, Brighton Fire, and Brighton Ambulance could all be dispatched to the scene.  This would result in three unique incidents, even though only one phone call was made.  It
				is possible to deduce the number of unique "events" based on the address that different entities are dispatched to, however this site does not, yet, provide that meta data.
				</p>
				<br>
				<br>
				
				<p class="tab">
				<b>Total Incident Types</b>
				</p>
				<p class="tab2">
				When a call comes into Monroe County 911 dispatch, the dispatcher needs to select the type of call it is.  An example of this would be "Barking Dog" or "hit and run, no injury 
				and no blocking".  There are a number of different incident types, this number represents the total different types seen by the web scrapers.
				</p>
				<br>
				<br>
				
				<p class="tab">
				<b>Total Status Types</b>
				</p>
				<p class="tab2">
				When a call comes in it immediately is placed into a "DISPATCHED" state.  There are a number of other states such as "ENROUTE" and "ONSCENE" an incident can have.  This site keeps
				track of when each incident moves between each status type.  This value represents the total number of status types seen by the web scrapers.
				</p>
				<br>
				<br>
				
<?php
	require_once("_footer.php");
?>